#User: Admin / zabbix
---
  - name: Basic configurations
    hosts: all
    become: yes
    gather_facts: true
    vars:
      DbServerName: icmp-db1.iservermate.local
      #ZabbixServerName: icmp-zabbix.iservermate.local
    
    tasks:
#ZABIX INSTALLATION
      - name: Install Zabbix Agent
        yum:
          name: https://repo.zabbix.com/zabbix/6.4/rhel/8/x86_64/zabbix-release-6.4-1.el8.noarch.rpm
          state: present
          validate_certs: no
          disable_gpg_check: yes

      - name: Install zabbix-agent
        yum:
          name: zabbix-agent
          state: latest

      - name: Reload Zabbix Agent
        ansible.builtin.service:
          name: zabbix-agent
          state: restarted
          enabled: yes

      - name: Configure Agent for monitoring
        ansible.builtin.lineinfile:
          path: /etc/zabbix/zabbix_agentd.conf
          regexp: '^Server=127.0.0.1'
          line: Server={{ DbServerName }}
        notify: Restart Zabbix

      - name: Configure Agent for monitoring
        ansible.builtin.lineinfile:
          path: /etc/zabbix/zabbix_agentd.conf
          regexp: '^ServerActive=127.0.0.1'
          line: ServerActive={{ DbServerName }}
        notify: Restart Zabbix

      - name: Configure Agent for monitoring
        ansible.builtin.lineinfile:
          path: /etc/zabbix/zabbix_agentd.conf
          regexp: '^Hostname=Zabbix server'
          line: "#Hostname=Zabbix server"
        notify: Restart Zabbix

    handlers:
      - name: Reload Zabbix Agent
        ansible.builtin.service:
          name: zabbix-agent
          state: restarted
          enabled: yes
        listen: "Restart Zabbix"