#User: Admin / zabbix
---
  - name: Basic configurations
    hosts: all
    become: yes
    gather_facts: true  
    tasks:
      - name: Update /etc/hosts file
        ansible.builtin.template:
          src: hosts.j2
          dest: /etc/hosts
