---
# tasks file for roles/database
  - import_tasks: mariadb.yml
    tags:
      - mariadbInstall

  - import_tasks: firewall.yml
    tags:
      - mariadbFirewall

  - import_tasks: gleracluster.yml
    tags:
      - mariadbGlera

  - import_tasks: dbfix.yml
    tags:
      - mariadbDbFix

  - import_tasks: zabbix_db.yml
    tags:
      - mariadbZabbixDb

  - import_tasks: remoteconnections.yml
    tags:
      - mariadbRemoteConnection
