---
# handlers file for roles/Zabbix
  - name: Reload Mariadb
    ansible.builtin.service:
      name: mariadb
      state: restarted
      enabled: yes
    listen: "mariadb restart"

  - name: Reload Zabbix Proxy service
    ansible.builtin.service:
      name: zabbix-proxy
      state: restarted
      enabled: yes
    listen: "Restart Zabbix-Proxy"

  - name: Reload Zabbix-server
    ansible.builtin.service:
      name: zabbix-server
      state: restarted
      enabled: yes
    ignore_errors: yes
    listen: "Restart Zabbix-server"
