---
  - name: Install Zabbix
    yum:
      name: https://repo.zabbix.com/zabbix/6.4/rhel/8/x86_64/zabbix-release-6.4-1.el8.noarch.rpm
      state: present
      validate_certs: no
      disable_gpg_check: yes
    when: ansible_hostname == "icmp-zabbix"

  - name: Switch DNF module version for PHP
    command: dnf module switch-to php:7.4 -y
    when: ansible_hostname == "icmp-zabbix"

  - name: Install Zabbix frontend
    yum:
      name: "{{ item }}"
      state: latest
    loop:
      - mysql
      - zabbix-server-mysql
      - zabbix-web-mysql
      - zabbix-apache-conf
    when: ansible_hostname == "icmp-zabbix"
       
  - name: Configure the Zabbix-Server for Connectivity with Database
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_server.conf
      regexp: '^# DBHost=localhost'
      line: DBHost={{ DbHostIp }}
    when: ansible_hostname == "icmp-zabbix"
    notify: Restart Zabbix-server

  - name: Configure the Zabbix-Server for Connectivity with Database
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_server.conf
      regexp: '^# DBPassword='
      line: DBPassword={{ db_pass }}
    when: ansible_hostname == "icmp-zabbix"
    notify: Restart Zabbix-server
      
  - name: Configure the Zabbix-Server for Unsupported DB Versions
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_server.conf
      regexp: '^# AllowUnsupportedDBVersions=0'
      line: AllowUnsupportedDBVersions=1
    when: ansible_hostname == "icmp-zabbix"
    notify: Restart Zabbix-server
      
  - name: Configure the Zabbix-Server for SourceIP
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_server.conf
      regexp: '^# SourceIP='
      line: SourceIP=0.0.0.0
    when: ansible_hostname == "icmp-zabbix"        
    notify: Restart Zabbix-server

  - name: Start Zabix service on icmp-zabbix
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - zabbix-server
      - httpd
      - php-fpm
    ignore_errors: yes
    when: ansible_hostname == "icmp-zabbix"