---
#ZABIX INSTALLATION
  - name: Install Zabbix proxy repo
    yum:
      name: https://repo.zabbix.com/zabbix/6.4/rhel/8/x86_64/zabbix-release-6.4-1.el8.noarch.rpm
      state: present
      validate_certs: no
      disable_gpg_check: yes
    when: ansible_hostname == "icmp-zproxy"

  - name: Install Packages
    yum:
      name: ['zabbix-proxy-mysql','zabbix-sql-scripts','zabbix-selinux-policy','mysql']
      state: latest
    when: ansible_hostname == "icmp-zproxy"

  - name: Configure the the proxy to allow Unsupported DB Version
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_proxy.conf
      regexp: '^# AllowUnsupportedDBVersions=0'
      line: AllowUnsupportedDBVersions=1
    when: ansible_hostname == "icmp-zproxy"
    notify: Restart Zabbix-Proxy

  - name: Configure the database Host for Zabbix proxy server
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_proxy.conf
      regexp: '^# DBHost=localhost'
      line: DBHost={{ DbHostIp }}
    when: ansible_hostname == "icmp-zproxy"
    notify: Restart Zabbix-Proxy

  - name: Configure the Zabbix-Server hostname in configuration file
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_proxy.conf
      regexp: '^Hostname=Zabbix proxy'
      line: Hostname={{ ZproxyHostname }}
    when: ansible_hostname == "icmp-zproxy"        
    notify: Restart Zabbix-Proxy

  - name: Configure the database name for Zabbix proxy server connectivity
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_proxy.conf
      regexp: '^DBName=zabbix_proxy'
      line: DBName={{ ZabbixProxyDb }}
    when: ansible_hostname == "icmp-zproxy"
    notify: Restart Zabbix-Proxy

  - name: Configure the database user for Zabbix proxy server
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_proxy.conf
      regexp: '^DBUser=zabbix'
      line: DBUser={{ ZabbixProxyDbUser }}
    when: ansible_hostname == "icmp-zproxy"
    notify: Restart Zabbix-Proxy

  - name: Configure the database password for Zabbix proxy server
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_proxy.conf
      regexp: '^# DBPassword='
      line: DBPassword={{ ZabbixProxyDbPass }}
    when: ansible_hostname == "icmp-zproxy"
    notify: Restart Zabbix-Proxy

  - name: Configure the Zabbix-Server IP in confguration file
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_proxy.conf
      regexp: '^Server=127.0.0.1'
      line: Server={{ ZabixServerIP }}
    when: ansible_hostname == "icmp-zproxy"        
    notify: Restart Zabbix-Proxy

  - name: Enable Active proxy mdoe in confguration file
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_proxy.conf
      regexp: '^# ProxyMode=0'
      line: ProxyMode=0
    when: ansible_hostname == "icmp-zproxy"        
    notify: Restart Zabbix-Proxy

  - name: Enable and set ProxyLocalBuffer in confguration file
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_proxy.conf
      regexp: '^# ProxyLocalBuffer=0'
      line: ProxyLocalBuffer=412
    when: ansible_hostname == "icmp-zproxy"        
    notify: Restart Zabbix-Proxy

  - name: Enable and set ProxyOfflineBuffer in confguration file
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_proxy.conf
      regexp: '^# ProxyOfflineBuffer=1'
      line: ProxyOfflineBuffer=512
    when: ansible_hostname == "icmp-zproxy"        
    notify: Restart Zabbix-Proxy

  - name: Enable and set ProxyConfigFrequency in confguration file
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_proxy.conf
      regexp: '^# ProxyConfigFrequency=10'
      line: ProxyConfigFrequency=600
    when: ansible_hostname == "icmp-zproxy"        
    notify: Restart Zabbix-Proxy

  - name: Enable and set StartIPMIPollers in confguration file
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_proxy.conf
      regexp: '^# StartIPMIPollers=0'
      line: StartIPMIPollers=2
    when: ansible_hostname == "icmp-zproxy"        
    notify: Restart Zabbix-Proxy

  - name: Enable and set StartVMwareCollectors in confguration file
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_proxy.conf
      regexp: '^# StartVMwareCollectors=0'
      line: StartVMwareCollectors=2
    when: ansible_hostname == "icmp-zproxy"        
    notify: Restart Zabbix-Proxy

  - name: Enable and set StartSNMPTrapper in confguration file
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_proxy.conf
      regexp: '^# StartSNMPTrapper=0'
      line: StartSNMPTrapper=1
    when: ansible_hostname == "icmp-zproxy"        
    notify: Restart Zabbix-Proxy

  - name: Enable and set StatsAllowedIP in confguration file
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_proxy.conf
      regexp: '^StatsAllowedIP=127.0.0.1'
      line: StatsAllowedIP=127.0.0.1,192.168.0.1/24
    when: ansible_hostname == "icmp-zproxy"        
    notify: Restart Zabbix-Proxy